### ISSUE TITLE
Error, when installing libraries or contract on testrpc

### ISSUE THREAD

**Issue by Mikefluff** [airalab/core#25]
$ testrpc -v
EthereumJS TestRPC v3.0.0
$ node -v
v6.9.1
$ npm -v
4.0.2

Mikes-MacBook-Air-2:core mikefluff$ ./aira_deploy.js -O -C AddressList --library
Compile...
(compiled)
/Volumes/USB/prog/Ethereum/core/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filename)

TypeError: cb is not a function
    at /Volumes/USB/prog/Ethereum/core/lib/compiler.js:70:17
    at /Volumes/USB/prog/Ethereum/core/node_modules/hash-files/lib/hash.js:69:4
    at /Volumes/USB/prog/Ethereum/core/node_modules/async/lib/async.js:726:13
    at /Volumes/USB/prog/Ethereum/core/node_modules/async/lib/async.js:52:16
    at replenish (/Volumes/USB/prog/Ethereum/core/node_modules/async/lib/async.js:306:28)
    at /Volumes/USB/prog/Ethereum/core/node_modules/async/lib/async.js:326:29
    at /Volumes/USB/prog/Ethereum/core/node_modules/async/lib/async.js:44:16
    at /Volumes/USB/prog/Ethereum/core/node_modules/async/lib/async.js:723:17
    at /Volumes/USB/prog/Ethereum/core/node_modules/async/lib/async.js:167:37
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)

Mikes-MacBook-Air-2:core mikefluff$ ./aira_deploy.sh -C Core -A '["MyDAO", "My first DAO"]' 
Compile...
(cache)

Contract:	Core
WARN: No libs loaded!
Binary size:	6.0859375K

Error: VM Exception while processing transaction: out of gas
    at Object.InvalidResponse (/Volumes/USB/prog/Ethereum/core/node_modules/web3/lib/web3/errors.js:35:16)
    at /Volumes/USB/prog/Ethereum/core/node_modules/web3/lib/web3/requestmanager.js:86:36
    at request.onreadystatechange (/Volumes/USB/prog/Ethereum/core/node_modules/web3/lib/web3/httpprovider.js:110:13)
    at dispatchEvent (/Volumes/USB/prog/Ethereum/core/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/Volumes/USB/prog/Ethereum/core/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/Volumes/USB/prog/Ethereum/core/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)

**Comment by akru** [comment]
Hey there!
So sorry for too long response.

I test your case and can give you a [video](https://cloud.mail.ru/public/3nGf/7m9xGB4K8).

I use:
* node: 7.5.0
* testrpc: 3.0.3
* airalab/core: latest
